### ISSUE TITLE
Escape to close window is super laggy

### ISSUE THREAD

**Issue by jmmanley** [sakethramanujam/gazetracker#10]
Hi, do you also experience a lot of lag when trying to close the tracker using the escape key? It takes me a least ~10 sec of holding the esc key on my MacBook for it close. I wonder if there's a better approach than what is implemented [currently](https://github.com/sakethramanujam/gazetracker/blob/e7648af88fc738689f550a963973713adb8236cc/tracker.py#L74-L77):
```
key_pressed = cv2.waitKey(30) & 0xff
if key_pressed == ESCAPE_KEY:
   break
```

**Comment by sakethramanujam** [comment]
@jmmanley for me, lag only happens when my pc is ram bottle necked by a background proved. Sounds interesting, shall check this out.

**Comment by sakethramanujam** [comment]
@fatkaratekid @Jac08H @shorrock can you people confirm this behaviour if you have a mac?

**Comment by fatkaratekid** [comment]
No issues with mac here
