### ISSUE TITLE
Transformation Function Required

### ISSUE THREAD

**Issue by sakethramanujam** [sakethramanujam/gazetracker#13]
The heat maps generated are localized to the image window. I need help to figure out, how to make a transformation function that also considers the angle at which the eye ball hits the screen!

**Comment by Klowner** [comment]
I can probably assist with this but I'm not perfectly clear on what transformation you need to perform. Is this just a matter of scaling up the calculated mouse coordinates to fill the entire display rather than just the space of the tiny window?

**Comment by sakethramanujam** [comment]
Yes!!!! It's what I wanted to achieve!
