### ISSUE TITLE
Coding Standards!

### ISSUE THREAD

**Issue by sakethramanujam** [sakethramanujam/gazetracker#6]
Does this code looks like it follows standards? or like quality code? Help me improve!

**Comment by shorrock** [comment]
I created a PR https://github.com/sakethramanujam/gazetracker/pull/11 generally showing some examples of how I might improve the code to be more readable and maintainable. In general https://www.python.org/dev/peps/pep-0008/ is a great resource if you want to learn more about writing higher-quality, more standards-compliant code in Python.

Good luck!

**Comment by aliciawyy** [comment]
Hi,
I have added a code climate config in https://github.com/sakethramanujam/gazetracker/pull/18 to help you detect coding standard violation. I have used this tool for some time, hope it will also be helpful to you.

Happy coding!
